### ISSUE TITLE
[Bug] input select styling docs

### ISSUE THREAD

**Issue by mvanleest** [creativetimofficial/ct-now-ui-kit-pro-react#1]
### Version
1.0.0
### Reproduction link
https://demos.creative-tim.com/now-ui-kit-pro-react/#/documentation/forms
### Operating System
macOS 10.14.5
### Device
MacBook Pro
### Browser & Version
Chrome 76.0.3809.100
### Steps to reproduce
1. Go to the sizing section ( https://demos.creative-tim.com/now-ui-kit-pro-react/#/documentation/forms )
2. Large, default and small selects are all styled as system default (no difference between them)
3. Also in the "Form row" section, the select is styled as system default.
### What is expected?
Styled selects like other form inputs.
### What is actually happening?
System default select styling is used.

---
### Solution
Update select styling or the docs.

**Comment by einazare** [comment]
Hello there, @mvanleest ,

Thank you for your interest in working with our products.
Those components should look like that, before launching them, I've spoken with my superiors about that issue, and they said it was ok.
I will forward your request to them as well.

Best,
Manu
