### ISSUE TITLE
[Bug] Build Issue with AWS

### ISSUE THREAD

**Issue by cnbrkkaya** [creativetimofficial/ct-now-ui-kit-pro-react#2]
### Version
latest
### Reproduction link
https://master.d1bhhsz8gxg2gx.amplifyapp.com/
### Operating System
AWS Amplify
### Device
Amplify
### Browser & Version
Chrome@latest
### Steps to reproduce
-I download product file i make custom configurations for my purpose. When i work with localhost everything is fine.
-I entegrate the project with Aws Amplify, i add authentication and other custom things , again localhost is fine there is no problem with cloud resources.
-Then i want to build the product and deploy to aws i get errors. But when i do exact steps without your product for example when i follow these steps with normal create-react-app application everything is fine.
### What is expected?
Build in aws resources and deploy correctly.
### What is actually happening?
I can deploy the product to 
"  https://master.d1bhhsz8gxg2gx.amplifyapp.com/    "
But I get these Errors

![5](https://user-images.githubusercontent.com/36765181/73068315-e9ef6780-3e78-11ea-8f0f-425e8f144066.JPG)
And here is my scripts in package.json 
`"scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "compile-sass": "node-sass src/assets/scss/now-ui-dashboard.scss src/assets/css/now-ui-dashboard.css",
    "minify-sass": "node-sass src/assets/scss/now-ui-dashboard.scss src/assets/css/now-ui-dashboard.min.css --output-style compressed",
    "map-sass": "node-sass src/assets/scss/now-ui-dashboard.scss src/assets/css/now-ui-dashboard.css --source-map true",
    "install:clean": "rm -rf node_modules/ && rm -rf package-lock.json && npm install && npm start"
  },`
Do i have to make any configuration for these scripts ?
---
### Solution
AWS use these template to build projects , maybe we need to make some configuration in the template for your product. Do i need to add additional build commands for your product ?

![3](https://user-images.githubusercontent.com/36765181/73068339-f8d61a00-3e78-11ea-93e6-46776f7e6d5f.JPG)

Thank you all  !

**Comment by einazare** [comment]
Hello there, @cnbrkkaya ,

Thank you for your interest in working with our products.
Please delete the homepage prop from our package.json, it points to our Github repository, and when you build the product, the built version will make the homepage prop as base href.

Let me know if that worked.

Best,
Manu

**Comment by cnbrkkaya** [comment]
Thanks for your help
I delete the homepage prop in package.json and everything is fine now.
