### ISSUE TITLE
[Bug] Can't be built on netlify

### ISSUE THREAD

**Issue by QzCurious** [creativetimofficial/ct-now-ui-kit-pro-react#6]
### Version
1.5.0
### Reproduction link
https://github.com/creativetimofficial/ct-now-ui-kit-pro-react/issues
### Operating System
N/A
### Device
N/A
### Browser & Version
N/A
### Steps to reproduce
1. upload to github
2. link to netfliy
3. delopy on netlify
### What is expected?
Applicable dependeny among all packages
### What is actually happening?
npm install failed

---
### Additional comments
For Link to minimal reproduction:
Sorry I should not make a public github project for this.

**Comment by sajadevo** [comment]
**Hi @QzCurious**

We've updated the product and the npm install failed issues is fixed now.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
