### ISSUE TITLE
[Bug] npm install doesn't work

### ISSUE THREAD

**Issue by karthikraja95** [creativetimofficial/ct-now-ui-kit-pro-react#7]
### Version
1.5.1
### Reproduction link
https://github.com/creativetimofficial/ct-now-ui-kit-pro-react/issues/5
### Operating System
macOS Monterey
### Device
12.5
### Browser & Version
Chrome latest
### Steps to reproduce
Download the latest version of the code from creative-tim website
Install node 16.16.0 Stable version
cd to the downloaded directory
npm install
### What is expected?
It should build the website locallay
### What is actually happening?
npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: now-ui-kit-pro-react@1.5.1
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.5.0 || ^17.0.0" from react-datetime@3.1.1
npm ERR! node_modules/react-datetime
npm ERR!   react-datetime@"3.1.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/kalaisel/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kalaisel/.npm/_logs/2022-08-11T17_11_45_242Z-debug-0.log

---
### Additional comments
I have creative-tim club pass, most of your codebase has dependency issues please resolve this, otherwise it's really difficult for us

**Comment by josue0ghost** [comment]
Solved running `npm install --legacy-peer-deps`

Changing peerDependencies didn't work. Would be nice they update the package.json with working fresh install dependencies

**Comment by waqiju** [comment]
I also meet the same problem, wonder if there are some better way to avoid it ?

**Comment by sajadevo** [comment]
This issue is fixed on v1.5.2.
